# Generated by Django 2.2.3 on 2019-07-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
