# Generated by Django 2.2.5 on 2019-09-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeProduit', models.CharField(max_length=200)),
                ('familleProduit', models.CharField(max_length=200)),
                ('descriptionProduit', models.CharField(max_length=200)),
                ('quantiteMin', models.PositiveIntegerField()),
                ('packaging', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
